### ISSUE TITLE
add JavaScript lang as well

### ISSUE THREAD

**Issue by dagolinuxoid** [ckcz123/codejam#3]
I am planning to spent some time on solving kickstart/codejam tasks. Rather than creating my own repo I decided to fork your codejam repo (since this one is well organized and good looking already) and make pull request to it. I think there is no need for creating separate sub folders for java and js - it's easy to distinguish between the source code by their extensions (even if in the future there would be proposals for Python let's say it's not a big deal). Are you interesting in accepting pull requests for js?

**Comment by ckcz123** [comment]
No problem, I'm glad about that.
And, as I didn't attend kickstart/codejam these two years, it's would be nice if you can fill the blank.
